# Site settings
title: George's Portfolio
email: georgeargiroudis@gmail.com
antispam_email:
  mail_name: georgeargiroudis
  mail_tail_reverse: moc.liamg
url: https://gargirou.github.io
description: "Welcome to my portfolio website. This space is designed to showcase a variety of projects from my personal, academic, and professional career."
meta_author: Argiroudis George #LastName FirstName
featured_img: portfolio-snapshot.jpg
profile_pic: profile-picture.png
# Google webmaster tools
google_verify: Zzy_rd0hz8T-8h0CVYkA2doONdaaO1DcEsgVtDrFMoQ

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify: C32940599ED0AC7E4A5EC182BDEE6E3E

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

#Header image. Insert image into url("")
header:
  bg-image: vancouver-dt-blur-bg.jpg

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 5289ce
  primary-rgb: "82, 137, 206"
  secondary: 2c3e50
  secondary-dark: 233140

# Footer settings
footer:
  copyright: George Argiroudis
  location: Contact
  social: Social
  credits: Credits
  services: Services

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/gargiroudis/
  - title: github
    url: http://github.com/gargirou
  - title: instagram
    url: https://www.instagram.com/geoargi/

# Postal address (add as many lines as necessary)
address:
  - line: Vancouver, BC

skills: "Web Developer - Software Engineer - IT Technician"

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: none
